# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x10\x63om.example.grpc\"\x1e\n\x0cStockRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"A\n\rStockResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\t2h\n\x14\x46inancialDataService\x12P\n\rGetStockPrice\x12\x1e.com.example.grpc.StockRequest\x1a\x1f.com.example.grpc.StockResponseB/\n\x10\x63om.example.grpcB\x19\x46inancialDataServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.example.grpcB\031FinancialDataServiceProtoP\001'
  _globals['_STOCKREQUEST']._serialized_start=35
  _globals['_STOCKREQUEST']._serialized_end=65
  _globals['_STOCKRESPONSE']._serialized_start=67
  _globals['_STOCKRESPONSE']._serialized_end=132
  _globals['_FINANCIALDATASERVICE']._serialized_start=134
  _globals['_FINANCIALDATASERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
